[project]
name = "remote_submitit_launcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["milatools>=0.1.5", "submitit>=1.5.2"]

[project.entry-points."submitit.executor"]
remote_slurm = "remote_slurm_launcher:RemoteSlurmExecutor"

[tool.uv]
dev-dependencies = ["pytest>=8.3.3"]
